<?php
function drustracof_menu() {
  $items = array();

  $items['drustracof_authorize'] = array(
    'page callback' => 'drustracof_authorize_callback',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'file' => 'drustracof_menu.inc'
  );

  $items['admin/config/drustracof'] = array(
    'title' => 'DruStraCof Management',
    'description' => 'Configure settings for DruStraCof.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drustracof_admin'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'drustracof_admin.inc'
  );

  return $items;
}

function drustracof_block_info() {
  $blocks = array();

  $blocks['strava_login'] = array(
    'info' => 'Strava Login',
  );

  return $blocks;
}

function drustracof_block_view($delta = '') {
  $block = array();

  $client_id = variable_get('drustracof_client_id', '');

  if (empty($client_id)) {
    return $block;
  }

  switch ($delta) {
    case 'strava_login' :
      if (user_is_logged_in()) {

      }
      else {
        $redirect_uri = url('drustracof_authorize', array('absolute' => TRUE));
        $block['content'] = l('Log in with Strava', 'https://www.strava.com/oauth/authorize', array('query' => array('response_type' => 'code', 'redirect_uri' => $redirect_uri, 'client_id' => $client_id)));
      }
      break;
  }

  return $block;
}